<?php

namespace Soyhuce\PhpunitToCobertura\Commands;

class HelpCommand implements Command
{
    public function run(): void
    {
        (new VersionCommand())->run();

        echo 'Converts your phpunit code coverage to a cobertura code coverage' . PHP_EOL;
        echo PHP_EOL;
        echo 'Usage:' . PHP_EOL;
        echo '  phpunit-to-cobertura [options] <input> <output>' . PHP_EOL;
        echo PHP_EOL;
        echo 'Arguments:' . PHP_EOL;
        echo "  <input>\t\t\tPath to the php coverage report generated by PHPUnit, required" . PHP_EOL;
        echo "  <output>\t\tWhere to generate cobertura coverage report, required" . PHP_EOL;
        echo PHP_EOL;
        echo 'Misc:' . PHP_EOL;
        echo "  -h|--help \t\t\tPrint this help" . PHP_EOL;
        echo "  --version \t\t\tShow PHPUnit to Cobertura version and exit" . PHP_EOL;
    }
}
